[params]
gct_file = ''
output_dir = ''  # optional; defaults to --output-dir or --data-dir

[params.norm]
normalize = false
log_transform = false
batch = ""  # leave unspecified for null

[params.filter]
non_zeros = 1.0
nonzero_subgroup = ''

[params.heatmap]
do = true
cut_by = ""
cluster_rows = true
cluster_columns = false
z_score = true
z_score_by = ""
legend_include = []
legend_exclude = []


[params.heatmap.selection]
# does nothing if no files present
do = true
id_column = "id"
file_list = [{}]

[params.pca]
do = true
color = "group"
marker = ""
max_pc = 3
scale = true
show_labels = true
width = 6.5
height = 7.2

[params.limma]
do = true
formula = "~0 + group"
contrasts = []
top_n = [25, 50, 75, 100]


[params.totalprotein]
do = true
volcanodir = ''
gct_prof = ''
genes = []
genes_file = ''
topn_genes = 0
group_var = ''
heatmap_meta_cols = []
heatmap_zscore = true

[params.qc]
do = true
level = 1
downsample_n = 200000

# "Level 2 QC" toggles (unsupervised summaries):
# - If `cor_do` is unset, correlations default to on at `level >= 2`.
cor_method = "pearson"
cor_use_zscore = false

# Prefer the main `[params.pca]` routine; QC PCA is off by default.
pca_do = false
pca_topn = 5000

[params.qc.missingness]
value_threshold = ''
# If `upset_do` is unset, UpSet defaults to on at `level >= 2` (requires ComplexUpset).
upset_top = 8
upset_min_intersections = 2
upset_max_features = 5000

[params.extra]
sample_order = []


[params.advanced]
cache = true
replace = true
